<a href="https://colab.research.google.com/github/Sonia-Carpediem/PythonBasics/blob/main/Pandas05_09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Pandas**

It is python library which is used for data manipulation,data analysis

- it helps in load, clean, transform, analyse, and exploring data easily

- it stands for panel data

who created pandas?

Wes McKinney
2008

Why was pandas created?

as we know numpy was used for working with numbers,array,mathematical operations

but real-world data is messy->missing value,duplicate value, mixed data,csv/excel/json

to handle real-world data problems pandas was created

Install pandas

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

Import the library

In [ ]:
import pandas as pd
#pd-->alias or nickname

How pandas work?

In [ ]:
#Pandas works with two structures :
#1.Series
#2.DataFrame

#**Series**

- it is one-dimensional labelled array

- it is simply one column data with index

- it can store numbers, string, boolean, mixed dtype

series=data+index

In [ ]:
#create a series

In [ ]:
s=pd.Series([20,1,30,24])
print(s,type(s))

0    20
1     1
2    30
3    24
dtype: int64 <class 'pandas.core.series.Series'>

In [ ]:
#list
l1=[1,2,4,5,'a']
s1=pd.Series(l1)
print(l1,type(l1))
print(s1,type(s1))

[1, 2, 4, 5, 'a'] <class 'list'>
0    1
1    2
2    4
3    5
4    a
dtype: object <class 'pandas.core.series.Series'>

In [ ]:
#tuple
t1=(12,3,4,57,'a')
s2=pd.Series(t1)
print(s2,type(s2))

0    12
1     3
2     4
3    57
4     a
dtype: object <class 'pandas.core.series.Series'>

In [ ]:
#numpy--->precedence: int<float<str
#pandas--->precedence:int<float<str

In [ ]:
#set--->list and then create it
se={1,2,4,5}
print(se)
s3=pd.Series(se)
print(s3,type(s3))

{1, 2, 4, 5}

TypeError: 'set' type is unordered

In [ ]:
#dictionary
#key--->index
#value--->data/value

In [ ]:
s4=pd.Series({'a':101,'b':102,'c':103})#a,b,c-->key and 101,102,103-->value
print(s4,type(s4))

a    101
b    102
c    103
dtype: int64 <class 'pandas.core.series.Series'>

Custom index

In [ ]:
s5=pd.Series([100,200,300,400],index=['a','b',1,2])
print(s5)

a    100
b    200
1    300
2    400
dtype: int64

In [ ]:
#series-->with customindex

In [ ]:
a=['english','hindi','maths','science']
s6=pd.Series([90,95,98,97],index=a)
print(s6)

english    90
hindi      95
maths      98
science    97
dtype: int64

Accessing elements in series

1.Label-based

In [ ]:
#accessing using label/index

In [ ]:
x1=pd.Series([30,40,50,60],index=['maths','english','science','hindi'])
print(x1)

maths      30
english    40
science    50
hindi      60
dtype: int64

In [ ]:
print(x1['hindi'])

60

In [ ]:
print(x1['science'])

50

Position based

In [ ]:
print(x1[1])

40

/tmp/ipykernel_508/1364225292.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(x1[1])

In [ ]:
print(x1[2])

50

/tmp/ipykernel_508/51412365.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(x1[2])

slicing

In [ ]:
print(x1)

maths      30
english    40
science    50
hindi      60
dtype: int64

In [ ]:
print(x1[0:2])#(start,end,step)-->endis exclusive so we write end+1

maths      30
english    40
dtype: int64

In [ ]:
print(x1['maths':'english'])#labelbased end is inclusive

maths      30
english    40
dtype: int64

.loc-->label based access(multiple)

- it is used to access data using index explicitly
- end is inclusive

In [ ]:
x2=pd.Series([100,200,'red',300],index=['red','green','yellow','orange'])
print(x2)

red       100
green     200
yellow    red
orange    300
dtype: object

In [ ]:
#single label
x2.loc['green']

200

In [ ]:
#multiple labels
x2.loc['green':'orange']

green     200
yellow    red
orange    300
dtype: object

In [ ]:
print(x2.loc[['green','yellow','orange']])

green     200
yellow    red
orange    300
dtype: object

2. iloc-->index based

In [ ]:
print(x2)

red       100
green     200
yellow    red
orange    300
dtype: object

In [ ]:
#single position
x2.iloc[0]

100

In [ ]:
#multiple position
print(x2.iloc[[1,2]])#but here i want list with 1 and 2 position
x2.iloc[1:2]#here 2 is exclusive

green     200
yellow    red
dtype: object

green    200
dtype: object

In [ ]:
print(x2)

red       100
green     200
yellow    red
orange    300
dtype: object

In [ ]:
x2.iloc[[0,2]]

red       100
yellow    red
dtype: object

In [ ]:
x3=pd.Series([1,2,3,4])
print(x3)
x3

0    1
1    2
2    3
3    4
dtype: int64

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
x3.loc[0]

np.int64(1)

In [ ]:
x3.loc[0:2]#inclusive

0    1
1    2
2    3
dtype: int64

In [ ]:
x3

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
x3.iloc[2]

np.int64(3)

In [ ]:
x3.iloc[0:4]#slicing based on index--->end is exclusive

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
x3.iloc[[0,3]]#give me list of 0,2--->gives list of series

0    1
3    4
dtype: int64

operations on series

In [ ]:
y1=pd.Series([10,20,30,40])
print(y1)

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
#scaler addtion
print(y1+5)

0    15
1    25
2    35
3    45
dtype: int64

In [ ]:
#scaler subtraction
print(y1-5)

0     5
1    15
2    25
3    35
dtype: int64

In [ ]:
print(y1*2)

0    20
1    40
2    60
3    80
dtype: int64

In [ ]:
print(y1/2)

0     5.0
1    10.0
2    15.0
3    20.0
dtype: float64

In [ ]:
#operation between 2 series

In [ ]:
s1=pd.Series([10,20,30],index=['a','b','c'])
s2=pd.Series([5,10,25],index=['a','c','d'])

In [ ]:
print(s1)

a    10
b    20
c    30
dtype: int64

In [ ]:
print(s2)

a     5
c    10
d    25
dtype: int64

In [ ]:
print(s1+s2)#performs operation wrt labels-->if not present returns not a number->NaN

a    15.0
b     NaN
c    40.0
d     NaN
dtype: float64

Statistical operation

In [ ]:
#np.mean(),np.median,np.max

In [ ]:
print(y1)

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
#-->describe()--it gives you statistical report

In [ ]:
y1.describe()

count     4.000000
mean     25.000000
std      12.909944
min      10.000000
25%      17.500000
50%      25.000000
75%      32.500000
max      40.000000
dtype: float64

In [ ]:
#unique()-->the uniques valuesin series/remove dupicate and give once
#nunique()--->the number of unique values

In [ ]:
x=pd.Series([10,20,30,40,10,80,'red','red','yellow'])

In [ ]:
print(x)

0        10
1        20
2        30
3        40
4        10
5        80
6       red
7       red
8    yellow
dtype: object

In [ ]:
x.unique()

array([10, 20, 30, 40, 80, 'red', 'yellow'], dtype=object)

In [ ]:
print(x)

0        10
1        20
2        30
3        40
4        10
5        80
6       red
7       red
8    yellow
dtype: object

In [ ]:
x.nunique()

7

Series *Manipulation*

- series manipulation refers to changing values, index

In [ ]:
print(y1)

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
y1[1]=33

In [ ]:
print(y1)

0    10
1    33
2    30
3    40
dtype: int64

In [ ]:
y1[3]=45

In [ ]:
print(y1)

0    10
1    33
2    30
3    45
dtype: int64

In [ ]:
#replace-->it will replace specific value
#but it will not affect originalseries
#series.replace(value_Replace,new_value)

In [ ]:
print(x2)

red       100
green     200
yellow    red
orange    300
dtype: object

In [ ]:
x2.replace('red','pink')

In [ ]:
#index manipulation

In [ ]:
s=pd.Series([300,400,500],index=['a','b','c'])

In [ ]:
print(s)

In [ ]:
#rename-->renames index labels without changing originalseries
#if use inplaceit changes original

In [ ]:
s.rename(index={'a':'alpha','b':'beta'},inplace=True)

In [ ]:
print(s)

0    20
1     1
2    30
3    24
dtype: int64

In [ ]:
#s.index=['x','y','c']

In [ ]:
#print(s)

Concatenation

In [ ]:
x1=pd.Series([10,200,300])
x2=pd.Series([200,5000,400,600],index=['a','b','c','d'])
print(pd.concat([x1,x2]))

0      10
1     200
2     300
a     200
b    5000
c     400
d     600
dtype: int64

In [ ]:
c=pd.Series([10,20,30])
new=pd.Series([15],index=[1])
s=pd.concat([c.iloc[:1],new,c.iloc[1:]]).reset_index(drop=True)
print(s)

0    10
1    15
2    20
3    30
dtype: int64

Condition and filtering

In [ ]:
marks=pd.Series([45,78,65,88,32])
print(marks)

0    45
1    78
2    65
3    88
4    32
dtype: int64

In [ ]:
marks>60

0    False
1     True
2     True
3     True
4    False
dtype: bool

In [ ]:
print(marks[marks>60])

1    78
2    65
3    88
dtype: int64

In [ ]:
#and--->&
#or--->|
#instead of writing not-->~

In [ ]:
print(marks[(marks>60)&(marks<80)])

1    78
2    65
dtype: int64

In [ ]:
print(marks[~(marks>60)])

0    45
4    32
dtype: int64

In [ ]:
#sorting

In [ ]:
print(marks)

0    45
1    78
2    65
3    88
4    32
dtype: int64

In [ ]:
marks.sort_values()#by defult it is ascending

4    32
0    45
2    65
1    78
3    88
dtype: int64

In [ ]:
marks.sort_values(ascending=False)

3    88
1    78
2    65
0    45
4    32
dtype: int64

In [ ]:
m=pd.Series([78,30,40,55],index=['a','z','b','x'])
print(m)

a    78
z    30
b    40
x    55
dtype: int64

In [ ]:
m.sort_index()

a    78
b    40
x    55
z    30
dtype: int64

DataFrame

- it is a 2d ,labelled,tabular,data structurein pandas

- table with rows and columns

-dataframe=multiple series aligned by index

In [ ]:
#syntax-->pd.DataFrame()

In [ ]:
#dict

In [ ]:
d1={'a':['raju','rafique','aajith'],'b':[101,102,103],'c':['green','yellow','red']}
print(d1)
#key-->colname
#value-->data

{'a': ['raju', 'rafique', 'aajith'], 'b': [101, 102, 103], 'c': ['green', 'yellow', 'red']}

In [ ]:
d=pd.DataFrame(d1)

In [ ]:
d

         a    b       c
0     raju  101   green
1  rafique  102  yellow
2   aajith  103     red

In [ ]:
#df=pd.read_csv('file path')
#df=pd.read_excel('filepath)

Basic Attributes of Data frame

In [ ]:
#df.shape()--->how many rows and columns

In [ ]:
d

         a    b       c
0     raju  101   green
1  rafique  102  yellow
2   aajith  103     red

In [ ]:
d.shape

(3, 3)

In [ ]:
#size()-->total elements
d.size

9

In [ ]:
d

         a    b       c
0     raju  101   green
1  rafique  102  yellow
2   aajith  103     red

In [ ]:
#columns--->it retuns the column name

In [ ]:
d.columns

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
d

         a    b       c
0     raju  101   green
1  rafique  102  yellow
2   aajith  103     red

In [ ]:
#index--->rowlabels
d.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
#dtypes-->tells the dtype

In [ ]:
d.dtypes

a    object
b     int64
c    object
dtype: object

view dataset

In [ ]:
#df.head()--->toprows
#working with large-->by default return 5

In [ ]:
d.head(2)

         a    b       c
0     raju  101   green
1  rafique  102  yellow

In [ ]:
#df.tail()-->it shows last  rows
#by default --->5

In [ ]:
d.tail(2)

         a    b       c
1  rafique  102  yellow
2   aajith  103     red

In [ ]:
#df.info()-->information about dataframe
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      object
 1   b       3 non-null      int64
 2   c       3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [ ]:
#create a series of 5 student marks and find average
#find highest and lowest
#print marks greater than 70
#create a series -->value ->marks and index->sub name

In [ ]:
import pandas as pd
# 1.
marks = pd.Series([85, 72, 65, 90, 78])
print("Marks:")
print(marks)
# 2.
print("Average:", marks.mean())
# 3.
print("Highest:", marks.max())
print("Lowest:", marks.min())
#or
print(marks.describe())
# 4.
print("Marks greater than 70:")
print(marks[marks > 70])

Marks:
0    85
1    72
2    65
3    90
4    78
dtype: int64
Average: 78.0
Highest: 90
Lowest: 65
count     5.000000
mean     78.000000
std       9.974969
min      65.000000
25%      72.000000
50%      78.000000
75%      85.000000
max      90.000000
dtype: float64
Marks greater than 70:
0    85
1    72
3    90
4    78
dtype: int64

In [ ]:
#4.
subjectmarks = pd.Series([85, 72, 65, 90, 78],index=["Maths", "Science", "English", "Computer", "History"])
print("Subject wise Marks:")
print(subjectmarks)

Subject wise Marks:
Maths       85
Science     72
English     65
Computer    90
History     78
dtype: int64